---
- name: Update Buildroot .config file
  hosts: all
  become: yes
  vars_files:
    - config/config.yml

  tasks:
    - name: Update .config file with new values
      ansible.builtin.lineinfile:
        path: ".config"
        line: "{{ item }}"
      loop: "{{ config_lines }}"

    - name: Build the kernel using Buildroot
      ansible.builtin.shell: 
        cmd: |
          cd buildroot && make -j $(nproc)