---
- name: Update Buildroot .config file and extract kernel version
  hosts: all
  become: yes
  vars_files:
    - config/config.yml

  tasks:
    - name: Update .config file with new values
      ansible.builtin.lineinfile:
        path: "buildroot/.config"
        regexp: '^{{ item.split("=")[0] }}=.*$'
        line: "{{ item }}"
      loop: "{{ config_lines }}"

    - name: Extract BR2_LINUX_KERNEL_VERSION
      shell: grep 'BR2_LINUX_KERNEL_VERSION=' buildroot/.config | cut -d'=' -f2 | tr -d '"'
      register: kernel_version_result
      changed_when: false

    - name: Build the kernel using a bash script with kernel version as argument
      ansible.builtin.script:
        cmd: "build_kernel.sh {{ kernel_version_result.stdout }}"
      when: kernel_version_result.stdout != ""
