config_lines:
  - 'BR2_LINUX_KERNEL=y'
  - 'BR2_LINUX_KERNEL_CUSTOM_VERSION=y'
  - 'BR2_LINUX_KERNEL_CUSTOM_VERSION_VALUE="5.10.8"'
  - 'BR2_LINUX_KERNEL_VERSION="5.10.8"'
  - 'BR2_LINUX_KERNEL_USE_ARCH_DEFAULT_CONFIG=y'
  - 'BR2_KERNEL_HEADERS_AS_KERNEL=y'
