# Use the official GCC image as the base
FROM ubuntu:latest

# Set the working directory
WORKDIR /

# Copy the precompiled binary into the container
COPY test /test

# Specify the default command to run the binary
CMD ["./test"]