# Use the official Python slim image
FROM python:3.9-slim

# Set up the working directory
WORKDIR /

# Copy the Python script into the container
COPY memory_limit.py /memory_limit.py

# Specify the default command
CMD ["python", "/memory_limit.py"]
